{pkgs}: {
  deps = [
    pkgs.freetype
    pkgs.fontconfig
    pkgs.gtk3
    pkgs.xorg.libXi
    pkgs.xorg.libXtst
    pkgs.xorg.libXrender
    pkgs.xorg.libxshmfence
    pkgs.libgbm
    pkgs.at-spi2-core
    pkgs.alsa-lib
    pkgs.cairo
    pkgs.pango
    pkgs.libxkbcommon
    pkgs.xorg.libxcb
    pkgs.expat
    pkgs.mesa
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libX11
    pkgs.dbus
    pkgs.libdrm
    pkgs.cups
    pkgs.at-spi2-atk
    pkgs.atk
    pkgs.nspr
    pkgs.nss
    pkgs.glib
  ];
}
