import { Router, type IRouter } from "express";
import authRouter from "./auth";
import scheduleRouter from "./schedule";
import visitsRouter from "./visits";
import transcribeRouter from "./transcribe";
import profileRouter from "./profile";
import documentsRouter from "./documents";
import messagingRouter from "./messaging";
import pushRouter from "./push";
import realtimeRouter from "./realtime";

const router: IRouter = Router();
router.use(authRouter);
router.use(scheduleRouter);
router.use(visitsRouter);
router.use(transcribeRouter);
router.use(profileRouter);
router.use(documentsRouter);
router.use(messagingRouter);
router.use(pushRouter);
router.use(realtimeRouter);
export default router;
