import { chromium } from "playwright";
const b = await chromium.launch({ headless: true });
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, timezoneId: "America/Los_Angeles", locale: "en-US" });
const p = await ctx.newPage();
p.on('console', m => console.log('[console]', m.type(), m.text().slice(0,200)));
p.on('pageerror', e => console.log('[pageerror]', e.message));
await p.goto("http://localhost:80/intake/ref_97a2797d-f3c", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(5000);
const text = await p.evaluate(() => document.body.innerText);
console.log("--- TEXT (first 1500) ---");
console.log(text.slice(0, 1500));
console.log("--- has digit%? ---", /\d{2,3}%/.test(text));
await b.close();
